### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.Build.Desktop_Player.Configuration
  commentId: T:Prowl.Editor.Build.Desktop_Player.Configuration
  id: Desktop_Player.Configuration
  parent: Prowl.Editor.Build
  children:
  - Prowl.Editor.Build.Desktop_Player.Configuration.Debug
  - Prowl.Editor.Build.Desktop_Player.Configuration.Release
  langs:
  - csharp
  - vb
  name: Desktop_Player.Configuration
  nameWithType: Desktop_Player.Configuration
  fullName: Prowl.Editor.Build.Desktop_Player.Configuration
  type: Enum
  source:
    remote:
      path: Prowl.Editor/Build/Desktop_Player.cs
      branch: development
      repo: git@github.com:brmassa/Prowl.git
    id: Configuration
    path: ../Prowl/Prowl.Editor/Build/Desktop_Player.cs
    startLine: 30
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Build
  syntax:
    content: public enum Desktop_Player.Configuration
    content.vb: Public Enum Desktop_Player.Configuration
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.Build.Desktop_Player.Configuration.Debug
  commentId: F:Prowl.Editor.Build.Desktop_Player.Configuration.Debug
  id: Debug
  parent: Prowl.Editor.Build.Desktop_Player.Configuration
  langs:
  - csharp
  - vb
  name: Debug
  nameWithType: Desktop_Player.Configuration.Debug
  fullName: Prowl.Editor.Build.Desktop_Player.Configuration.Debug
  type: Field
  source:
    remote:
      path: Prowl.Editor/Build/Desktop_Player.cs
      branch: development
      repo: git@github.com:brmassa/Prowl.git
    id: Debug
    path: ../Prowl/Prowl.Editor/Build/Desktop_Player.cs
    startLine: 32
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Build
  syntax:
    content: Debug = 0
    return:
      type: Prowl.Editor.Build.Desktop_Player.Configuration
- uid: Prowl.Editor.Build.Desktop_Player.Configuration.Release
  commentId: F:Prowl.Editor.Build.Desktop_Player.Configuration.Release
  id: Release
  parent: Prowl.Editor.Build.Desktop_Player.Configuration
  langs:
  - csharp
  - vb
  name: Release
  nameWithType: Desktop_Player.Configuration.Release
  fullName: Prowl.Editor.Build.Desktop_Player.Configuration.Release
  type: Field
  source:
    remote:
      path: Prowl.Editor/Build/Desktop_Player.cs
      branch: development
      repo: git@github.com:brmassa/Prowl.git
    id: Release
    path: ../Prowl/Prowl.Editor/Build/Desktop_Player.cs
    startLine: 33
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Build
  syntax:
    content: Release = 1
    return:
      type: Prowl.Editor.Build.Desktop_Player.Configuration
references:
- uid: Prowl.Editor.Build
  commentId: N:Prowl.Editor.Build
  href: Prowl.html
  name: Prowl.Editor.Build
  nameWithType: Prowl.Editor.Build
  fullName: Prowl.Editor.Build
  spec.csharp:
  - uid: Prowl
    name: Prowl
    href: Prowl.html
  - name: .
  - uid: Prowl.Editor
    name: Editor
    href: Prowl.Editor.html
  - name: .
  - uid: Prowl.Editor.Build
    name: Build
    href: Prowl.Editor.Build.html
  spec.vb:
  - uid: Prowl
    name: Prowl
    href: Prowl.html
  - name: .
  - uid: Prowl.Editor
    name: Editor
    href: Prowl.Editor.html
  - name: .
  - uid: Prowl.Editor.Build
    name: Build
    href: Prowl.Editor.Build.html
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  href: Prowl.html
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
    href: Prowl.html
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
    href: Prowl.Runtime.html
  spec.vb:
  - uid: Prowl
    name: Prowl
    href: Prowl.html
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
    href: Prowl.Runtime.html
- uid: Prowl.Editor.Build.Desktop_Player.Configuration
  commentId: T:Prowl.Editor.Build.Desktop_Player.Configuration
  parent: Prowl.Editor.Build
  href: Prowl.Editor.Build.Desktop_Player.html
  name: Desktop_Player.Configuration
  nameWithType: Desktop_Player.Configuration
  fullName: Prowl.Editor.Build.Desktop_Player.Configuration
  spec.csharp:
  - uid: Prowl.Editor.Build.Desktop_Player
    name: Desktop_Player
    href: Prowl.Editor.Build.Desktop_Player.html
  - name: .
  - uid: Prowl.Editor.Build.Desktop_Player.Configuration
    name: Configuration
    href: Prowl.Editor.Build.Desktop_Player.Configuration.html
  spec.vb:
  - uid: Prowl.Editor.Build.Desktop_Player
    name: Desktop_Player
    href: Prowl.Editor.Build.Desktop_Player.html
  - name: .
  - uid: Prowl.Editor.Build.Desktop_Player.Configuration
    name: Configuration
    href: Prowl.Editor.Build.Desktop_Player.Configuration.html
